"""first commit

Revision ID: 399b94ed2cda
Revises: 
Create Date: 2023-06-06 13:26:05.330502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399b94ed2cda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
