"""getting tables wrking

Revision ID: 3ab0331848b6
Revises: faaf309bbedf
Create Date: 2023-06-06 19:39:26.253740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab0331848b6'
down_revision = 'faaf309bbedf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enemy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enemy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('hp', sa.FLOAT(), nullable=True),
    sa.Column('xp_given', sa.INTEGER(), nullable=True),
    sa.Column('intellect', sa.INTEGER(), nullable=True),
    sa.Column('speed', sa.INTEGER(), nullable=True),
    sa.Column('strength', sa.INTEGER(), nullable=True),
    sa.Column('weapon', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
