"""getting tables wrking

Revision ID: 3abae350a50f
Revises: f08a2fe67c64
Create Date: 2023-06-06 20:11:18.614380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abae350a50f'
down_revision = 'f08a2fe67c64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
