"""getting enemy tables wrking

Revision ID: 525346bbc135
Revises: 7e1d06fb5030
Create Date: 2023-06-06 23:21:54.233170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525346bbc135'
down_revision = '7e1d06fb5030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
