"""getting enemy tables wrking

Revision ID: 7e1d06fb5030
Revises: d619a4a22b49
Create Date: 2023-06-06 23:09:49.875454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1d06fb5030'
down_revision = 'd619a4a22b49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
