"""current player established

Revision ID: 82e16b9c9de6
Revises: a72cfcc9e291
Create Date: 2023-06-06 16:50:11.408688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e16b9c9de6'
down_revision = 'a72cfcc9e291'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ability_name', sa.VARCHAR(), nullable=True),
    sa.Column('weapon_ability', sa.VARCHAR(), nullable=True),
    sa.Column('companion_ability', sa.VARCHAR(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
