"""trying to fix enemy table 

Revision ID: 8fa9ca9d87a9
Revises: 82e16b9c9de6
Create Date: 2023-06-06 19:22:59.668180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa9ca9d87a9'
down_revision = '82e16b9c9de6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
