"""message

Revision ID: 9d5c9dc0ade1
Revises: 8fa9ca9d87a9
Create Date: 2023-06-06 19:24:43.033131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5c9dc0ade1'
down_revision = '8fa9ca9d87a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
