"""fngers crossed

Revision ID: a72cfcc9e291
Revises: 399b94ed2cda
Create Date: 2023-06-06 13:32:16.564782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72cfcc9e291'
down_revision = '399b94ed2cda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
