"""getting enemy tables wrking

Revision ID: e0f079b5d2fc
Revises: 525346bbc135
Create Date: 2023-06-06 23:30:56.959312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f079b5d2fc'
down_revision = '525346bbc135'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('primary_attack', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('secondary_attack', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player', 'abilities', ['primary_attack'], ['id'])
    op.create_foreign_key(None, 'player', 'abilities', ['secondary_attack'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'secondary_attack')
    op.drop_column('player', 'primary_attack')
    # ### end Alembic commands ###
