"""getting tables wrking

Revision ID: f08a2fe67c64
Revises: 3ab0331848b6
Create Date: 2023-06-06 20:08:24.492452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08a2fe67c64'
down_revision = '3ab0331848b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enemy')
    op.drop_table('ability')
    op.drop_table('abilities')
    op.add_column('player', sa.Column('intellect', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'intellect')
    op.create_table('abilities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ability_name', sa.VARCHAR(), nullable=True),
    sa.Column('weapon_ability', sa.VARCHAR(), nullable=True),
    sa.Column('companion_ability', sa.VARCHAR(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ability',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ability_name', sa.VARCHAR(), nullable=True),
    sa.Column('weapon_ability', sa.VARCHAR(), nullable=True),
    sa.Column('companion_ability', sa.VARCHAR(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enemy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('hp', sa.FLOAT(), nullable=True),
    sa.Column('xp_given', sa.INTEGER(), nullable=True),
    sa.Column('intellect', sa.INTEGER(), nullable=True),
    sa.Column('speed', sa.INTEGER(), nullable=True),
    sa.Column('strength', sa.INTEGER(), nullable=True),
    sa.Column('weapon', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
