"""getting tables wrking

Revision ID: faaf309bbedf
Revises: 9d5c9dc0ade1
Create Date: 2023-06-06 19:26:32.187463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faaf309bbedf'
down_revision = '9d5c9dc0ade1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
